# Generated by Django 5.0.14 on 2026-09-14 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='合订本条码')),
                ('label', models.CharField(max_length=200, verbose_name='合订本题名')),
                ('status', models.CharField(choices=[('ACTIVE', '在订'), ('UNBOUND', '已拆订')], default='ACTIVE', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='装订时间')),
                ('unbound_at', models.DateTimeField(blank=True, null=True, verbose_name='拆订时间')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REGULAR', '正期'), ('SUPPLEMENT', '增刊'), ('COMBINED', '合期')], default='REGULAR', max_length=12, verbose_name='期类型')),
                ('pub_year', models.PositiveIntegerField(verbose_name='发行年')),
                ('pub_month', models.PositiveSmallIntegerField(verbose_name='发行月')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='卷')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='期号（起）')),
                ('number_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='期号（止，仅合期）')),
                ('supplement_no', models.PositiveSmallIntegerField(default=0, verbose_name='增刊序号')),
                ('copies_checked_in', models.PositiveIntegerField(default=0, verbose_name='累计入藏册数')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='备注')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pub_year', 'pub_month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='位置代码')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='条码')),
                ('copy_no', models.PositiveIntegerField(verbose_name='复本号')),
                ('status', models.CharField(choices=[('ON_SHELF', '在架'), ('BOUND', '已装订')], default='ON_SHELF', max_length=10, verbose_name='状态')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('bound_volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_items', to='serials.boundvolume', verbose_name='所在合订本')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='serials.issue', verbose_name='所属期')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serials.location', verbose_name='当前位置')),
            ],
            options={
                'ordering': ['issue_id', 'copy_no'],
            },
        ),
        migrations.CreateModel(
            name='BoundVolumeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='册序')),
                ('pre_status', models.CharField(choices=[('ON_SHELF', '在架'), ('BOUND', '已装订')], max_length=10, verbose_name='装订前状态')),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('unbound_at', models.DateTimeField(blank=True, null=True)),
                ('bound_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bound_items', to='serials.boundvolume', verbose_name='合订本')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binding_records', to='serials.item', verbose_name='册')),
                ('pre_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serials.location', verbose_name='装订前位置')),
            ],
            options={
                'ordering': ['bound_volume_id', 'position'],
            },
        ),
        migrations.AddField(
            model_name='boundvolume',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='serials.location', verbose_name='当前位置'),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='刊名')),
                ('issn', models.CharField(blank=True, default='', max_length=9, verbose_name='ISSN')),
                ('frequency', models.CharField(choices=[('MONTHLY', '月刊'), ('BIMONTHLY', '双月刊'), ('QUARTERLY', '季刊'), ('SEMIANNUAL', '半年刊'), ('ANNUAL', '年刊')], default='MONTHLY', max_length=20, verbose_name='出版频率')),
                ('start_year', models.PositiveIntegerField(verbose_name='创刊年')),
                ('start_month', models.PositiveSmallIntegerField(default=1, verbose_name='创刊月')),
                ('volume_start_number', models.PositiveIntegerField(default=1, verbose_name='起始卷号')),
                ('volume_start_year', models.PositiveIntegerField(verbose_name='首卷起始年')),
                ('volume_start_month', models.PositiveSmallIntegerField(default=1, verbose_name='首卷起始月')),
                ('months_per_volume', models.PositiveSmallIntegerField(default=12, verbose_name='每卷跨越月数')),
                ('status', models.CharField(choices=[('ACTIVE', '在版'), ('CEASED', '停刊')], default='ACTIVE', max_length=10, verbose_name='出版状态')),
                ('ceased_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='停刊年')),
                ('ceased_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='停刊月')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='serials.title', verbose_name='前身刊')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHECK_IN', '入藏'), ('BIND', '合订'), ('UNBIND', '拆订'), ('MOVE_ITEM', '册移库'), ('MOVE_VOLUME', '合订本移库'), ('ISSUE_REGISTER', '期登记'), ('TITLE_CEASE', '停刊登记')], max_length=20, verbose_name='操作类型')),
                ('actor', models.CharField(default='system', max_length=64, verbose_name='操作人')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='明细')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bound_volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='serials.boundvolume')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serials.location')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serials.issue')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='serials.item')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='serials.location')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='serials.title')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='serials.title', verbose_name='刊名'),
        ),
        migrations.AddField(
            model_name='boundvolume',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bound_volumes', to='serials.title', verbose_name='刊名'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('issue', 'copy_no'), name='uniq_item_issue_copy'),
        ),
        migrations.AddConstraint(
            model_name='boundvolumeitem',
            constraint=models.UniqueConstraint(fields=('bound_volume', 'item'), name='uniq_bv_item'),
        ),
        migrations.AddConstraint(
            model_name='boundvolumeitem',
            constraint=models.UniqueConstraint(fields=('bound_volume', 'position'), name='uniq_bv_position'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('title', 'kind', 'volume', 'number', 'number_end', 'supplement_no'), name='uniq_issue_identity'),
        ),
    ]
